---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.17
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.17
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.17
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.17
  i386: ghcr.io/home-assistant/i386-base-python:3.11-alpine3.17
args:
  UNIVERSAL_SILABS_FLASHER: 0.0.15
